version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: assetflow_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nisarg@2006
      POSTGRES_DB: assetflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
