export const AppEvents = {
  // Asset
  ASSET_ASSIGNED: 'ASSET_ASSIGNED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  ASSET_TRANSFER_REQUESTED: 'ASSET_TRANSFER_REQUESTED',
  ASSET_TRANSFER_APPROVED: 'ASSET_TRANSFER_APPROVED',

  // Booking
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_REMINDER: 'BOOKING_REMINDER',

  // Maintenance
  MAINTENANCE_REQUESTED: 'MAINTENANCE_REQUESTED',
  MAINTENANCE_APPROVED: 'MAINTENANCE_APPROVED',
  MAINTENANCE_REJECTED: 'MAINTENANCE_REJECTED',
  MAINTENANCE_RESOLVED: 'MAINTENANCE_RESOLVED',

  // Audit
  AUDIT_CREATED: 'AUDIT_CREATED',
  AUDIT_ASSIGNED: 'AUDIT_ASSIGNED',
  AUDIT_DISCREPANCY_FOUND: 'AUDIT_DISCREPANCY_FOUND',
  AUDIT_CLOSED: 'AUDIT_CLOSED',

  // System
  OVERDUE_RETURN: 'OVERDUE_RETURN',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
} as const;

export type AppEvent = typeof AppEvents[keyof typeof AppEvents];
